myproject/myproject/urls.py
from django.conf.urls import url
from django.contrib import admin
from cabshare import views
from django.contrib.auth.models import User
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', views.view_cabs, name='home'),
    url(r'^view_cabs/$', views.view_cabs, name='view_cabs'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^approve_cab/(?P<pk_cab>[\w.@+-]+)/for_user/(?P<pk_user>[\w.@+-]+)/$', views.approve_cab, name='approve_cab'),
    url(r'^decline_cab/(?P<pk_cab>[\w.@+-]+)/for_user/(?P<pk_user>[\w.@+-]+)/$', views.decline_cab, name='decline_cab'),
    url(r'^contact_details/(?P<pk>\d+)/$', views.contact_details, name='contact_details'),
    url(r'^not_authorized/$', views.contact_details, name='not_authorized'),

    url(r'^user_info_for_new_cab/$', views.user_info_for_new_cab, name='user_info_for_new_cab'),
    url(r'^user_info_for_user_details/$', views.user_info_for_user_details, name='user_info_for_user_details'),
    url(r'^user_info_for_admin_panel/$', views.user_info_for_admin_panel, name='user_info_for_admin_panel'),
    url(r'^user_info_for_request_cab/(?P<pk>\d+)/$', views.user_info_for_request_cab, name='user_info_for_request_cab'),
    url(r'^cab_info/(?P<pk>\d+)/$', views.cab_info, name='cab_info'),
    url(r'^(?P<username>[\w.@+-]+)/new_cab/$', views.new_cab, name='new_cab'),
    url(r'^(?P<username>[\w.@+-]+)/user_details/$', views.user_details, name='user_details'),
    url(r'^(?P<username>[\w.@+-]+)/cab_admin_panel/$', views.cab_admin_panel, name='cab_admin_panel'),
    url(r'^(?P<username>[\w.@+-]+)/manage_cab/(?P<pk>\d+)/$', views.manage_cab, name='manage_cab'), 
    url(r'^admin/', admin.site.urls),
]

myproject/cabshare/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class User_details(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    gender = models.CharField(max_length=1) # male = m, female = f, other = o
    dob = models.DateField()
    contact_no = models.IntegerField()
    contact_sharing = models.BooleanField(default=False)
    user = models.ForeignKey(User, related_name='user')

class Cab(models.Model):
    source = models.CharField(max_length=20) 
    destination = models.CharField(max_length=20)
    dep_date_time = models.DateTimeField()
    size = models.IntegerField()
    cab_admin = models.ForeignKey(User, related_name='cab_admin')
    created_at = models.DateTimeField(auto_now_add=True)

class Passengers(models.Model):
    user = models.ForeignKey(User, related_name='passangers')
    of_cab = models.ForeignKey(Cab, related_name='of_cab')
    is_cab_admin = models.BooleanField()
    approval_status = models.CharField(max_length=1) # requested = r, approved = a, declined = d

    

myproject/templates/base.html
{% load static %}<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Travel Buddy{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% block stylesheet %}{% endblock %} 
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'view_cabs' %}">Travel Buddy</a>
          <div class="" id="mainMenu">
              {% if user.is_authenticated %}
                <form class="form-inline ml-auto">
                  <a href="{% url 'logout' %}" class="btn btn-outline-secondary">Log out</a>
                  <a href="#" class="btn btn-primary ml-2">{{ user.username }}</a> <!--add user details url-->
                </form>
              {% else %}
                <form class="form-inline ml-auto">
                  <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log in</a>
                  <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up</a>
                </form>
              {% endif %}
            </div>
      </div>
    </nav>

      {% block content %}
      {% endblock %}

  </body>
</html>

myproject/templates/cab_admin_panel.html
{% extends "base.html" %}
{% block content %}
<br>
<div class="container">
        <h1>This is your Admin Panel {{ User.username }} !</h1> 
</div>
<br>

<div class="container">
<table class="table">
    <thead class="thead-inverse">
    <tr>
        <th>From</th>
        <th>To</th>
        <th>Date and Time</th>
        <th>Manage</th>
    </tr>
    </thead>
    <tbody>
    {% for cab in cabs %}
        <tr>
        <td> {{ cab.source }} </td>
        <td> {{ cab.destination }} </td>
        <td class="align-middle"> {{ cab.dep_date_time }} </td>
        <td class="align-middle"> <a href="{% url 'manage_cab' pk=cab.pk username=User.username %}"><button class="btn btn-success">Manage Cab</button></a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>
</div>  

{% endblock %}

myproject/templates/cab_info.html
{% extends "base.html" %}
{% block content %}
<br>
<div class="container">
    <h1> Cab Info </h1>
</div>
<br>


<div class="container">
    <div class="ml-4 mb-4">
    Source - <span class="font-weight-bold">{{ cab.source }}</span>
    </div>
    <div class="ml-4 mb-4">
        Destination - <span class="font-weight-bold">{{ cab.destination }}</span>
    </div>
    <div class="ml-4 mb-4">
        Date and Timing - <span class="font-weight-bold">{{ cab.dep_date_time }}</span>
    </div>
    <div class="ml-4 mb-4">
        Cab size - <span class="font-weight-bold">{{ cab.size }}</span>
    </div>
    <div class="ml-4 mb-4">
        Cab Admin - <span class="font-weight-bold">{{ cab.cab_admin }}</span>
    </div>
</div>


<div class="container">
    <br>
    <h1 class="mb-4"> Passengers </h1>
<table class="table center">
    <thead class="thead-inverse">
    <tr>
        <th>Username</th>
        <th>Status</th>
    </tr>
    </thead>
    <tbody>
        {% for passenger in passengers %}
            <tr>
            {% if passenger.is_cab_admin %}
            <td class="align-middle"> {{ passenger.user }} </td>
            <td class="align-middle"> a (Cab Admin)</td>
            {% else %}
            <td class="align-middle"> {{ passenger.user }} </td>
            <td class="align-middle"> 
                {{ passenger.approval_status }} </td>
            </tr>
            {% endif %}
        {% endfor %}
    </tbody>
</table>
</div>
<br>


<div class="row mx-auto" style="width: 300px;">
    <div class="ml-4 mb-4">
        <a href="{% url 'view_cabs' %}" class="btn btn-primary"> <-- Back</a>
    </div>
    <form method="post" novalidate>
        {% csrf_token %}
    <div class="ml-4 mb-4">
            <button type="submit" class="btn btn-primary btn-block">Request</button>
    </div>
    </form>
    {% if contact_access %}
    <div class="ml-4 mb-4">
            <a href={% url 'contact_details' pk=cab.pk %}><button type="submit" class="btn btn-success btn-block"> 📞 View contact details</button></a>
    </div>
    {% endif %}
</div>


{% endblock %}

myproject/templates/login.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}


{% block content %}

<br>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10 col-sm-12">
            <div class="card">
                <div class="card-body">
                <h3 class="card-title text-center">Log in</h3>
                <form method="post" novalidate>
                  {% csrf_token %}
                  <input type="hidden" name="next" value="{{ next }}">
                  {% include 'includes/form.html' %}
                  <button type="submit" class="btn btn-primary btn-block">Log in</button>
                </form>
                </div>
                <div class="card-footer text-muted text-center">
                    New to Travel Buddy? <a href="{% url 'signup' %}">Sign up</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

<!--

<div class="container">
    <div class="mb-4"></div>
    <h2 class="mb-4">Sign up</h2>
    <form method="post" novalidate>
      {% csrf_token %}
      {% include 'includes/form.html' %}
      <button type="submit" class="btn btn-primary">Create an account</button>
    </form>
</div>
-->

myproject/templates/manage_cab.html
{% extends "base.html" %}
{% block content %}
<br>
<div class="container">
    <h1> Cab Info </h1>
</div>
<br>


<div class="container">
    <div class="ml-4 mb-4">
    Source - <span class="font-weight-bold">{{ cab.source }}</span>
    </div>
    <div class="ml-4 mb-4">
        Destination - <span class="font-weight-bold">{{ cab.destination }}</span>
    </div>
    <div class="ml-4 mb-4">
        Date and Timing - <span class="font-weight-bold">{{ cab.dep_date_time }}</span>
    </div>
    <div class="ml-4 mb-4">
        Cab size - <span class="font-weight-bold">{{ cab.size }}</span>
    </div>
    <div class="ml-4 mb-4">
        Cab Admin - <span class="font-weight-bold">{{ cab.cab_admin }}</span>
    </div>
</div>


<div class="container">
    <br>
    <h1 class="mb-4"> Passengers </h1>
<table class="table">
    <thead class="thead-inverse">
    <tr>
        <th>Username</th>
        <th>Admin</th>
        <th>Status</th>
        <th>Approve</th>
        <th>Decline</th>
    </tr>
    </thead>
    <tbody>
        {% for passenger in passengers %}
            <tr>
            <td class="align-middle"> {{ passenger.user }} </td>
            <td class="align-middle"> {{ passenger.is_cab_admin }} </td>
            <td class="align-middle"> {{ passenger.approval_status }} </td>
            {% if passenger.is_cab_admin %}
            <td class="align-middle"> - </td>
            <td class="align-middle"> - </td>    
            {% else %}
            <td class="align-middle">
                <a href="{% url 'approve_cab' pk_cab=cab.pk pk_user=passenger.user.username %}"> <button class="btn btn-success"> Approve </button> </a>
            </td>
            <td class="align-middle">
                <a href="{% url 'decline_cab' pk_cab=cab.pk pk_user=passenger.user.username %}"> <button class="btn btn-danger"> Decline </button> </a>
            </td>
            {% endif %}
            </tr>
        {% endfor %}
    </tbody>
</table>
</div>
<br>


<div class="row mx-auto" style="width: 300px;">
    <div class="ml-4 mb-4">
        <a href="{% url 'view_cabs' %}" class="btn btn-primary"> <-- Back</a>
    </div>
</div>

{% endblock %}

myproject/templates/new_cab.html
{% extends "base.html" %}
{% block content %}
<br>
<div class="container">
    <h1>Hello {{ User.username }} !</h1> 
    <small class="text-muted d-block"> Please fill the following details. </small>
</div>
    <div class="container">
    <br>
<form method="post">
    {% csrf_token %}
    <div class="form-group">
    <label for="id_source">Source</label>
    <input type="text" class="form-control" id="id_source" name="source">
    </div-->

  <div class="form-group">
    <label for="id_destination">Destination</label>
    <input type="text" class="form-control" id="id_destination" name="destination">
  </div>
    <div class="form-group">
        <label for="id_dep_date">Departure date</label>
        <input type="date" class="form-control" id="id_dep_date" name="dep_date">
    </div>
    <div class="form-group">
        <label for="id_dep_time">Departure time</label>
        <input type="time" class="form-control" id="id_dep_time" name="dep_time" />
    </div>

    <div class="form-group">
            <label for="id_size">Cab Size</label> <br>
            <select class="form-control" id="id_size" name="size">
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
            <option value="6">6</option>
            <option value="7">7</option>
        </select>
    </div>
    <br>
    <button type="submit" class="btn btn-success">Post New Cab</button>
</form>
</div>
{% endblock %}

myproject/templates/not_authorized.html
{% extends "base.html" %}
{% block content %}
<br>
<div class="container">
    <h4> NOT AUTHORIZED ❌ </h4>
</div>
{% endblock %}

myproject/templates/signup.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}


{% block content %}

<br>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10 col-sm-12">
            <div class="card">
                <div class="card-body">
                <h3 class="card-title text-center">Sign up</h3>
                <form method="post" novalidate>
                  {% csrf_token %}
                  {% include 'includes/form.html' %}
                  <button type="submit" class="btn btn-primary btn-block">Create an account</button>
                </form>
                </div>
                <div class="card-footer text-muted text-center">
                    Already have an account? <a href="{% url 'login' %}">Log in</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

<!--

<div class="container">
    <div class="mb-4"></div>
    <h2 class="mb-4">Sign up</h2>
    <form method="post" novalidate>
      {% csrf_token %}
      {% include 'includes/form.html' %}
      <button type="submit" class="btn btn-primary">Create an account</button>
    </form>
</div>
-->

myproject/templates/user_details.html
{% extends "base.html" %}
{% block content %}
<br>
<div class="container">
    <h1>Hello {{ User.username }} !</h1> 
    <small class="text-muted d-block"> Please complete your user profile by entering the following details. </small>
</div>
<div class="container">
    <br>
<form method="post">
  {% csrf_token %}
  <!--div class="form-group">
    <label for="id_user_details_id">User Name</label>
    <input type="text" class="form-control" id="id_user_details_id" name="user_details_id">
    </div-->

  <div class="form-group">
    <label for="id_first_name">First Name</label>
    <input type="text" class="form-control" id="id_first_name" name="first_name">
  </div>
    <div class="form-group">
        <label for="id_last_name">Last Name</label>
        <input type="text" class="form-control" id="id_last_name" name="last_name">
    </div>

    <div class="form-group">
        <label for="id_gender">Gender</label> <br>
    <input type="radio" name="gender" value="m" class=""> Male
        <input type="radio" name="gender" value="f" class=""> Female
        <input type="radio" name="gender" value="o" class=""> Other
    </div>

    <div class="form-group">
        <label for="id_dob">Date of birth</label>
        <input type="text" class="form-control" id="id_dob" name="dob" value></textarea>
    </div>


    <div class="form-group">
        <label for="id_contact_no">Contact Number</label>
        <input type="text" class="form-control" id="id_contact_no" name="contact_no" value></textarea>
    </div>

    <div class="form-group">
        <label for="id_contact_sharing">Share Contact</label> <br>
        <input type="radio" name="contact_sharing" value="1" class=""> Yes
        <input type="radio" name="contact_sharing" value="0" class=""> No
    </div>
    <br>
    <button type="submit" class="btn btn-success">Update Details</button>
</form>
</div>
{% endblock %}

myproject/templates/user_info_for_admin_panel.html
{% extends "base.html" %}
{% block content %}
<br>
<div class="container">
        <h4> On your way to the Admin Panel 🖥 </h4>
    <small class="text-muted d-block"> Please enter a valid username. </small>
</div>
<div class="container">
    <br>
<form method="post">
  {% csrf_token %}
  <div class="form-group">
    <label for="id_username">Username</label>
    <input type="text" class="form-control" id="id_username" name="username">
    </div>

    <br>
    <button type="submit" class="btn btn-success">Submit</button>
</form>
</div>
{% endblock %}

myproject/templates/user_info_for_new_cab.html
{% extends "base.html" %}
{% block content %}
<br>
<div class="container">
        <h4> New Cab Ahead --> </h4>
    <small class="text-muted d-block"> Please enter a valid username. </small>
</div>
<div class="container">
    <br>
<form method="post">
  {% csrf_token %}
  <div class="form-group">
    <label for="id_username">Username</label>
    <input type="text" class="form-control" id="id_username" name="username">
    </div>

    <br>
    <button type="submit" class="btn btn-success">Submit</button>
</form>
</div>
{% endblock %}

myproject/templates/user_info_for_request_cab.html
{% extends "base.html" %}
{% block content %}
<br>
<div class="container">
        <h4> Just 1 step away from requesting cab 😀 </h4>
    <small class="text-muted d-block"> Please enter a valid username. </small>
</div>
<div class="container">
    <br>
<form method="post">
  {% csrf_token %}
  <div class="form-group">
    <label for="id_username">Username</label>
    <input type="text" class="form-control" id="id_username" name="username">
    </div>

    <br>
    <button type="submit" class="btn btn-success">Submit</button>
</form>
</div>
{% endblock %}

myproject/templates/user_info_for_user_details.html
{% extends "base.html" %}
{% block content %}
<br>
<div class="container">
        <h4> User Details Ahead --> </h4>
    <small class="text-muted d-block"> Please enter a valid username. </small>
</div>
<div class="container">
    <br>
<form method="post">
  {% csrf_token %}
  <div class="form-group">
    <label for="id_username">Username</label>
    <input type="text" class="form-control" id="id_username" name="username">
    </div>

    <br>
    <button type="submit" class="btn btn-success">Submit</button>
</form>
</div>
{% endblock %}

myproject/templates/view_cabs.html
{% extends 'base.html' %}

{% block content %}
    <div class = "container">
        <br>
        <h1>Cabs</h1>
        <br>
        <div class="row mx-auto" style="width: 500px;">
        {% if user.is_authenticated %}
        <div class="ml-4 mb-4">
                <a href="{% url 'new_cab' username=user.username %}" class="btn btn-primary">New Cab</a>
        </div>
        <div class="ml-4 mb-4">
                <a href="{% url 'user_details' username=user.username %}" class="btn btn-primary">User Details</a>
        </div>
        <div class="ml-4 mb-4">
                <a href="{% url 'cab_admin_panel' username=user.username %}" class="btn btn-primary">Admin Panel</a>
        </div>
        {% else %}
        <div class="ml-4 mb-4">
                <a href="{% url 'login' %}" class="btn btn-primary">New Cab</a>
        </div>
        <div class="ml-4 mb-4">
                <a href="{% url 'login'%}" class="btn btn-primary">User Details</a>
        </div>
        <div class="ml-4 mb-4">
                <a href="{% url 'login'%}" class="btn btn-primary">Admin Panel</a>
        </div>
        {% endif %}

    </div>
            <table class="table">
                <thead class="thead-inverse">
                <tr>
                    <th>From</th>
                    <th>To</th>
                    <th>Date and Time</th>
                    <th>Cab Admin</th>
                    <th>Current Passengers</th>
                </tr>
                </thead>
                <tbody>
                {% for cabs in cabs %}
                    <tr>
                    <td> {{ cabs.source }} </td>
                    <td> {{ cabs.destination }} </td>
                    <td class="align-middle"> {{ cabs.dep_date_time }} </td>
                    <td class="align-middle"> 
                        {{ cabs.cab_admin}} </td>
                    <td class="align-middle"> <a href="{% url 'cab_info' cabs.pk %}"><button class="btn btn-info">View Info</button></a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>  
{% endblock %}
 